---
- name: restart apache
  service:
    name: "{{ webserver_service_name }}"
    state: restarted

- name: reload apache
  service:
    name: "{{ webserver_service_name }}"
    state: reloaded
